CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS roles (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO roles (name)
VALUES ('admin'), ('moderator'), ('creator'), ('viewer')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS users (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username      VARCHAR(100) UNIQUE NOT NULL,
  email         VARCHAR(255) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role_id       INTEGER NOT NULL REFERENCES roles(id),
  avatar_url    TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS channels (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  name        VARCHAR(255) NOT NULL,
  description TEXT,
  banner_url  TEXT,
  avatar_url  TEXT,
  category    VARCHAR(50),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS videos (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id    UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  title         VARCHAR(500) NOT NULL,
  description   TEXT,
  category      VARCHAR(50),
  hls_url       TEXT,
  thumbnail_url TEXT,
  duration      INTEGER NOT NULL DEFAULT 0,
  status        VARCHAR(50) NOT NULL DEFAULT 'processing',
  views         INTEGER NOT NULL DEFAULT 0,
  tags          JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_videos_channel ON videos(channel_id);
CREATE INDEX IF NOT EXISTS idx_videos_created_at ON videos(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_videos_status ON videos(status);
CREATE INDEX IF NOT EXISTS idx_videos_status_created ON videos(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_videos_status_views ON videos(status, views DESC);
CREATE INDEX IF NOT EXISTS idx_videos_status_category_created ON videos(status, category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_videos_status_category_views ON videos(status, category, views DESC);
CREATE INDEX IF NOT EXISTS idx_videos_channel_status_created ON videos(channel_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_videos_category ON videos(category);
CREATE INDEX IF NOT EXISTS idx_videos_search ON videos USING GIN (to_tsvector('simple', title || ' ' || COALESCE(description, '')));

CREATE TABLE IF NOT EXISTS shorts (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id    UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  title         VARCHAR(500) NOT NULL,
  description   TEXT,
  video_url     TEXT NOT NULL,
  thumbnail_url TEXT,
  duration      INTEGER NOT NULL DEFAULT 0,
  views         INTEGER NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE IF EXISTS shorts ADD COLUMN IF NOT EXISTS description TEXT;
CREATE INDEX IF NOT EXISTS idx_shorts_created_at ON shorts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_shorts_channel ON shorts(channel_id);
CREATE INDEX IF NOT EXISTS idx_shorts_views_created ON shorts(views DESC, created_at DESC);

CREATE TABLE IF NOT EXISTS live_streams (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id   UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  title        VARCHAR(500) NOT NULL,
  stream_key   VARCHAR(255) UNIQUE NOT NULL,
  status       VARCHAR(50) NOT NULL DEFAULT 'idle',
  viewer_count INTEGER NOT NULL DEFAULT 0,
  hls_url      TEXT,
  thumbnail_url TEXT,
  category     VARCHAR(50),
  started_at   TIMESTAMPTZ NULL,
  ended_at     TIMESTAMPTZ NULL
);
CREATE INDEX IF NOT EXISTS idx_streams_status ON live_streams(status);
CREATE INDEX IF NOT EXISTS idx_streams_channel ON live_streams(channel_id);
CREATE INDEX IF NOT EXISTS idx_streams_status_started ON live_streams(status, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_streams_status_viewers ON live_streams(status, viewer_count DESC);
CREATE INDEX IF NOT EXISTS idx_streams_status_category_viewers ON live_streams(status, category, viewer_count DESC);
CREATE INDEX IF NOT EXISTS idx_streams_category ON live_streams(category);

CREATE TABLE IF NOT EXISTS subscriptions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  subscriber_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  channel_id    UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(subscriber_id, channel_id)
);
CREATE INDEX IF NOT EXISTS idx_subs_channel ON subscriptions(channel_id);
CREATE INDEX IF NOT EXISTS idx_subs_channel_subscriber ON subscriptions(channel_id, subscriber_id);

CREATE TABLE IF NOT EXISTS comments (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id   UUID NULL REFERENCES videos(id) ON DELETE CASCADE,
  short_id   UUID NULL REFERENCES shorts(id) ON DELETE CASCADE,
  parent_id  UUID NULL REFERENCES comments(id) ON DELETE CASCADE,
  content    TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (((video_id IS NOT NULL)::int + (short_id IS NOT NULL)::int) = 1)
);
CREATE INDEX IF NOT EXISTS idx_comments_video ON comments(video_id);
CREATE INDEX IF NOT EXISTS idx_comments_short ON comments(short_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent ON comments(parent_id);
CREATE INDEX IF NOT EXISTS idx_comments_video_created ON comments(video_id, created_at);

CREATE TABLE IF NOT EXISTS reactions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_type VARCHAR(50) NOT NULL,
  target_id   UUID NOT NULL,
  type        VARCHAR(50) NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, target_type, target_id)
);
CREATE INDEX IF NOT EXISTS idx_reactions_target ON reactions(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_reactions_target_type ON reactions(target_type, target_id, type);

CREATE TABLE IF NOT EXISTS watch_history (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id         UUID NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  watched_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  progress_seconds INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_watch_user ON watch_history(user_id);
CREATE INDEX IF NOT EXISTS idx_watch_user_video ON watch_history(user_id, video_id);

CREATE TABLE IF NOT EXISTS chat_messages (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stream_id  UUID NOT NULL REFERENCES live_streams(id) ON DELETE CASCADE,
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content    TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_chat_stream ON chat_messages(stream_id, created_at);

CREATE TABLE IF NOT EXISTS stream_signals (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stream_id  UUID NOT NULL REFERENCES live_streams(id) ON DELETE CASCADE,
  viewer_id  VARCHAR(120) NOT NULL,
  type       VARCHAR(40) NOT NULL,
  payload    TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_stream_signals ON stream_signals(stream_id, type, viewer_id, created_at);

CREATE TABLE IF NOT EXISTS reports (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_type VARCHAR(50) NOT NULL,
  target_id   UUID NOT NULL,
  reason      TEXT NOT NULL,
  status      VARCHAR(50) NOT NULL DEFAULT 'pending',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);

CREATE TABLE IF NOT EXISTS notifications (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  actor_id   UUID NULL REFERENCES users(id) ON DELETE SET NULL,
  type       VARCHAR(50) NOT NULL,
  title      VARCHAR(255) NOT NULL,
  body       VARCHAR(500) NULL,
  link       VARCHAR(500) NULL,
  thumbnail  VARCHAR(500) NULL,
  read_at    TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_notif_user_created ON notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notif_user_unread ON notifications(user_id, read_at);
